// Optional visual/browser integration check. Requires Playwright and Chromium.
// OMS_BROWSER_PATH may point to an existing Chromium binary.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.OMS_BROWSER_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});const artifacts=process.env.OMS_SCREENSHOT_DIR;const errors=[];const page=await browser.newPage({viewport:{width:1366,height:900}});page.on('pageerror',e=>errors.push(e.message));let remoteRequests=0;page.on('request',r=>{if(/^https?:/.test(r.url()))remoteRequests++;});
await page.goto('file://'+path.resolve(__dirname,'../play.html'));assert(await page.locator('#welcome').isVisible());await page.locator('#begin').click();await page.locator('#pause').click();assert.equal(await page.locator('.crew-token').count(),18);
if(artifacts){fs.mkdirSync(artifacts,{recursive:true});await page.screenshot({path:path.join(artifacts,'workshop-desktop.png'),fullPage:true});}
const advance=async minute=>page.evaluate(min=>{const s=OMSGame.state;while(s.time<min-1e-8&&!s.ended)OMS.advance(s,true);OMSGame.render();},minute);
await advance(6);await page.locator('[data-group="G"]').click();await page.locator('#select-two').click();await page.locator('[data-dest="A"]').click();assert.equal(await page.locator('#crew-T .crew-token').count(),2);
await advance(8);assert(await page.locator('#gadget-machine').evaluate(n=>n.classList.contains('broken')));await page.locator('[data-tech]').click();await page.locator('[data-dest="R"]').click();await advance(10);assert(await page.locator('#rush-dialog').isVisible());await page.locator('[data-rush="12"]').click();assert.equal(await page.evaluate(()=>OMSGame.state.rushChoice),12);
await advance(13);assert.equal(await page.evaluate(()=>OMSGame.state.machine),'fixed');await page.locator('[data-tech]').click();await page.locator('[data-dest="A"]').click();await advance(18);await page.locator('[data-group="D"]').click();await page.locator('#select-two').click();await page.locator('[data-dest="G"]').click();await advance(33);
await page.evaluate(()=>{OMSGame.select([12,13]);});await page.locator('[data-dest="D"]').click();await page.evaluate(()=>OMSGame.select([2,3,4,5]));await page.locator('[data-dest="B"]').click();await advance(45);assert(await page.locator('#results').isVisible());assert.match(await page.locator('#result-stats').innerText(),/60\/60/);assert.equal(await page.locator('.result-order').count(),4);
if(artifacts)await page.screenshot({path:path.join(artifacts,'workshop-results.png'),fullPage:true});await page.locator('#rematch').click();assert.equal(await page.evaluate(()=>OMSGame.state.time),0);assert.equal(await page.evaluate(()=>OMSGame.state.rushChoice),null);assert.equal(await page.locator('.crew-token').count(),18);
await page.locator('#pace').click();assert.match(await page.locator('#pace').innerText(),/Slower/);await page.locator('#motion').check();assert(await page.locator('body').evaluate(n=>n.classList.contains('less-motion')));
await page.locator('#pause').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>OMSGame.state.paused),false);await page.locator('h1').click();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>OMSGame.state.paused),true);
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));if(artifacts)await page.screenshot({path:path.join(artifacts,'workshop-mobile.png'),fullPage:true});assert.equal(errors.length,0,errors.join('\n'));assert.equal(remoteRequests,0);console.log('PASS: opening, 18 crew, transfers, repair, rush, full 60/60 shift, results, rematch, pace, reduced motion, keyboard, mobile overflow; zero page errors or remote requests.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
