const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('../src/engine.js');
function to(s,t){while(s.tick<Math.round(t/E.STEP)&&!s.ended)E.advance(s,true);}
function policy(name,rush){const s=E.create();const commands={360:()=>E.assign(s,[0,1],'A'),480:()=>name==='early'?E.assign(s,[6,7],'R'):E.assign(s,[6,7,0,1],'M'),600:()=>E.chooseRush(s,rush),660:()=>name==='bypass'&&E.assign(s,[6,7],'R'),780:()=>name==='early'&&E.assign(s,[6,7],'A'),960:()=>name==='bypass'&&E.assign(s,[6,7],'A'),1080:()=>E.assign(s,[12,13],'G'),1980:()=>{E.assign(s,[12,13],'D');if(!s.queue.G)E.assign(s,[2,3,4,5],'B');}};while(!s.ended){commands[s.tick]?.();E.advance(s,true);}return s;}
test('pause freezes every piece of state',()=>{const s=E.create();const before=JSON.stringify(s);for(let i=0;i<100;i++)E.advance(s);assert.equal(JSON.stringify(s),before);});
test('transfer takes one minute and cannot duplicate crew or retarget in transit',()=>{const s=E.create();assert(E.assign(s,[0,0],'A').ok);assert.equal(s.crew[0].location,'T');assert.equal(E.assign(s,[0],'D').ok,false);to(s,1);E.advance(s,true);assert.equal(s.crew[0].location,'A');assert.equal(s.crew.length,18);});
test('rush is once-only, arrives once, and auto-pauses at offer',()=>{const s=E.create();to(s,10);assert(s.paused&&s.rushOffered);assert(E.chooseRush(s,12));assert.equal(E.chooseRush(s,6),false);to(s,12);assert(s.rushArrived);assert.equal(Object.values(s.queue).reduce((a,b)=>a+b,0)+s.delivered,60);to(s,13);E.assertState(s);});
test('expired rush defaults to none',()=>{const s=E.create();to(s,12);assert.equal(s.rushChoice,0);assert.equal(E.chooseRush(s,12),false);assert.equal(s.orders[3].available,false);});
test('repair needs both techs; interruption retains progress',()=>{const s=E.create();to(s,8);assert.equal(E.assign(s,[0],'R').ok,false);E.assign(s,[6],'R');to(s,10);assert.equal(s.repair,0);E.assign(s,[7],'R');to(s,12);assert(s.repair>.9&&s.repair<1.1);const progress=s.repair;E.assign(s,[6],'A');to(s,14);assert.equal(s.repair,progress);assert(E.assign(s,[6],'R').ok);to(s,19);assert.equal(s.machine,'fixed');assert.equal(s.repair,4);assert.equal(s.repairActive,false);});
test('unsupervised manual crew cannot produce',()=>{const s=E.create();to(s,8);E.assign(s,[8,9,10,11],'M');const before=s.queue.A;to(s,11);assert(s.queue.A>=before);assert.equal(s.lastRates.A,0);});
test('repairing with both techs cannot also supervise manual work',()=>{const s=E.create();to(s,8);E.assign(s,[6,7],'R');E.assign(s,[8,9,10,11],'M');to(s,11);assert(s.repair>0);assert.equal(s.lastRates.A,0);});
test('exhaustion forces recovery and releases at 40',()=>{const s=E.create();s.crew[0].energy=19;E.advance(s,true);assert(s.crew[0].forcedRest);assert.equal(s.crew[0].target,'B');to(s,2);assert.equal(s.crew[0].location,'B');assert.equal(E.assign(s,[0],'A').ok,false);to(s,8);assert(s.crew[0].energy>=40);assert(E.assign(s,[0],'A').ok);});
test('late deliveries never change on-time deadline counts',()=>{const s=E.create();to(s,15);const onTime=s.orders[0].onTime;E.assign(s,[6,7],'R');to(s,25);assert(s.orders[0].delivered>=onTime);assert.equal(s.orders[0].onTime,onTime);});
test('early/full and bypass/half meet every accepted deadline',()=>{for(const [p,n] of [['early',12],['bypass',6]]){const s=policy(p,n);assert.equal(E.result(s).onTime,48+n,`${p}: ${JSON.stringify(E.result(s))}`);assert(s.orders.every(o=>!o.quantity||o.onTime===o.quantity));assert.equal(s.time,45);assert(s.orders.every(o=>o.closed));}});
test('tested bypass/full plan overcommits',()=>{const s=policy('bypass',12);assert(E.result(s).onTime<60);assert.equal(s.orders[3].onTime,12);});
test('identical commands reproduce all results and events',()=>assert.deepEqual(policy('early',12),policy('early',12)));
test('terminal state cannot advance or accept moves',()=>{const s=policy('early',12);const before=JSON.stringify(s);E.advance(s,true);assert.equal(E.assign(s,[0],'A').ok,false);assert.equal(JSON.stringify(s),before);});
test('rematch has no prior energy, commitments or repair',()=>{policy('early',12);assert.deepEqual(E.create(),E.create());const s=E.create();assert.equal(s.delivered,0);assert.equal(s.repair,0);assert.equal(s.rushChoice,null);assert(s.crew.every(w=>w.energy===75));});
test('arbitrary reassignment maintains inventory, crew and allocation',()=>{const s=E.create();let seed=17;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};while(!s.ended){if(s.tick%37===0)E.assign(s,[Math.floor(rand()*18)],['G','A','D','M','R','B'][Math.floor(rand()*6)]);if(s.tick===600)E.chooseRush(s,12);E.advance(s,true);E.assertState(s);}assert(s.orders.every(o=>o.closed));});
