const test=require('node:test'),assert=require('node:assert/strict'),E=require('../src/engine.js');
function run(policy,seed='major',goal='gathering'){const s=E.create(seed,goal);let guard=0;while(!s.ended&&guard++<60){policy(s);E.assert(s);}assert(s.ended);return s;}
const pick=(s,...ids)=>{for(const id of ids){const o=E.options(s).find(o=>o.id===id);if(o&&!E.reason(s,o))return E.choose(s,id);}throw Error('No feasible choice at '+s.day+' '+s.phase);};
function balanced(s){if(s.phase==='food')return pick(s,'planned','hardship');if(s.phase==='plan'){if(s.week===1)E.action(s,'shift');if(s.week===3)E.action(s,'rest');return pick(s,'continue');}return pick(s,...({3:['cafe','decline'],5:['inspect','fix','ack','wait'],8:['pass'],10:['promise'],12:['garden','pass'],14:['repair','ack','defer'],17:['pass'],19:['pass'],22:['ack'],24:['goal','wait'],26:['help','boundary'],28:['finish','goal']}[s.day]));}
function recovery(s){if(s.phase==='food')return s.week===3?pick(s,'planned','hardship'):pick(s,'quick','planned','hardship');if(s.phase==='plan'){if(s.week===1){E.action(s,'shift');E.action(s,'rest');}if(s.week===2)E.action(s,'rest');return pick(s,'continue');}return pick(s,...({3:['decline'],5:['wait'],8:['lamp','pass'],10:['boundary'],12:['pass'],14:['repair','ack','defer'],17:['shift90','rest','pass'],19:['pass'],22:['ack'],24:['goal','wait'],26:['boundary'],28:['goal','finish']}[s.day]));}
function spender(s){if(s.phase==='food')return pick(s,'quick','hardship');if(s.phase==='plan')return pick(s,'continue');return pick(s,...({3:['cafe','decline'],5:['wait'],8:['lamp','pass'],10:['promise'],12:['garden','pass'],14:['repair','defer','ack'],17:['shift90','rest','pass'],19:['speaker','pass'],22:['ack'],24:['goal','wait'],26:['delivery','boundary'],28:['goal','finish']}[s.day]));}
test('balanced, recovery and spending policies complete with distinct outcomes',()=>{const a=run(balanced),b=run(recovery,'major','course'),c=run(spender);assert.equal(a.paid.length,7);assert(a.goalDone);assert.equal(b.paid.length,7);assert(b.goalDone);assert.notDeepEqual(E.result(a),E.result(b));assert.notDeepEqual(E.result(b),E.result(c));});
test('invalid choice does not mutate state',()=>{const s=E.create();const before=JSON.stringify(s);assert.equal(E.choose(s,'nope').ok,false);assert.equal(JSON.stringify(s),before);});
test('shift cap and energy/block restrictions are explicit',()=>{const s=E.create();E.choose(s,'quick');assert(E.action(s,'shift').ok);assert.match(E.reason(s,E.actions(s)[0]),/already/);s.energy=10;s.shiftWeek=0;assert.match(E.reason(s,E.actions(s)[0]),/energy/);});
test('same strategy and seed reproduce every ledger and outcome',()=>assert.deepEqual(run(balanced),run(balanced)));
test('payday arrives once before day 8 food plan and rent pays on day 9',()=>{const s=E.create();pick(s,'planned');pick(s,'continue');pick(s,'decline');pick(s,'wait');assert.equal(s.day,8);assert.equal(s.phase,'food');assert.equal(s.ledger.filter(x=>x.label==='Paycheck').length,1);pick(s,'planned');pick(s,'continue');pick(s,'pass');assert(s.paid.includes('Rent · week 2'));});
test('late bill keeps full balance, charges once, and settles on income',()=>{const s=E.create();pick(s,'quick');pick(s,'continue');pick(s,'cafe');pick(s,'wait');assert(s.journal.some(x=>x.text.includes('outstanding')));assert(s.paid.includes('Phone'));assert.equal(s.debts.length,0);assert.equal(s.ledger.filter(x=>x.label.includes('Phone · overdue')).length,1);});
test('inspection reveals and repair resolves known cost',()=>{const s=E.create('minor');pick(s,'planned');E.action(s,'shift');pick(s,'continue');pick(s,'decline');pick(s,'inspect');assert.equal(s.bike,'minor');const before=s.cash;assert(E.action(s,'fix').ok);assert.equal(before-s.cash,20);assert(s.repaired);});
test('time replenishes rather than accumulates and energy stays capped',()=>{const s=E.create();pick(s,'planned');E.action(s,'rest');E.action(s,'rest');assert.equal(s.energy,100);pick(s,'continue');pick(s,'decline');pick(s,'wait');assert.equal(s.blocks,3);assert.equal(s.energy,90);});
test('forecast includes future bills and labels payday',()=>{const s=E.create();const f=E.forecast(s);assert.equal(f.payday,8);assert.equal(f.afterKnown,80);});
test('ended run rejects events and optional actions without changes',()=>{const s=run(balanced),before=JSON.stringify(s);assert.equal(E.choose(s,'goal').ok,false);assert.equal(E.action(s,'rest').ok,false);assert.equal(JSON.stringify(s),before);});
if(process.env.PAYDAY_LEDGER){const fs=require('node:fs');const rows=['strategy,day,item,change,balance'];const results=[];for(const [name,policy,goal] of [['balanced',balanced,'gathering'],['recovery',recovery,'course'],['spending',spender,'gathering']]){const s=run(policy,'major',goal);results.push({strategy:name,...E.result(s)});for(const r of s.ledger)rows.push([name,r.day,'"'+r.label.replaceAll('"','""')+'"',r.change,r.balance].join(','));}fs.writeFileSync(process.env.PAYDAY_LEDGER,rows.join('\n')+'\n');console.log(JSON.stringify(results,null,2));}
test('resting on day 26 does not silently revise a promise',()=>{const s=E.create();s.day=26;s.week=4;s.phase='event';s.promise=true;assert(E.action(s,'rest').ok);assert.equal(s.promise,true);assert.equal(s.flags.length,0);});
test('varied available decisions preserve resources and finish a bounded month',()=>{let n=98765;const rand=m=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n%m;};for(let k=0;k<150;k++){const s=E.create(k%2?'minor':'major',k%3?'course':'gathering');for(let j=0;j<80&&!s.ended;j++){const a=E.actions(s).filter(o=>!E.reason(s,o));if(a.length&&rand(3)===0)E.action(s,a[rand(a.length)].id);const c=E.options(s).filter(o=>!E.reason(s,o));assert(c.length,'No available decision');E.choose(s,c[rand(c.length)].id);E.assert(s);}assert(s.ended);assert.equal(s.ledger.filter(x=>x.label==='Paycheck').length,2);}});
